# Generated by Django 3.0.2 on 2020-01-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_feedposts'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsarticle',
            name='hash_tags',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
