# Generated by Django 3.0.2 on 2020-01-16 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_postsarticle_hash_tags'),
        ('hashing', '0002_auto_20200116_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_hashing',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hash', to='post.PostsArticle'),
        ),
        migrations.AlterField(
            model_name='sub_hashing',
            name='feed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hash', to='post.FeedPosts'),
        ),
    ]
