# Generated by Django 3.0.2 on 2020-01-17 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('hashing', '0003_auto_20200116_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashing',
            name='key',
        ),
        migrations.RemoveField(
            model_name='sub_hashing',
            name='article',
        ),
        migrations.RemoveField(
            model_name='sub_hashing',
            name='feed',
        ),
        migrations.AddField(
            model_name='sub_hashing',
            name='field_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='sub_hashing',
            name='object_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sub_hashing',
            name='tag_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='hashing.hashing'),
        ),
        migrations.RemoveField(
            model_name='hashing',
            name='hash',
        ),
        migrations.AddField(
            model_name='hashing',
            name='hash',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
