# Generated by Django 3.0.3 on 2020-03-07 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rooms',
            old_name='room',
            new_name='room_name',
        ),
    ]
