# Generated by Django 3.0.3 on 2020-03-08 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20200307_2249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connections',
            old_name='room',
            new_name='rooms',
        ),
    ]
