# Generated by Django 3.0.3 on 2020-03-08 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20200308_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connections',
            old_name='rooms',
            new_name='room',
        ),
    ]
