# Generated by Django 3.0.3 on 2020-03-08 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20200308_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connections',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chat.rooms'),
        ),
    ]
